name: 'sensor_data_data'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sensor_data'

# Where dbt should look for models and tests
model-paths: ["models"]
test-paths: ["tests"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  sensor_data_data:
    # Staging models: Bronze → Silver
    staging:
      +schema: silver
      +materialized: table
    
    # Mart models: Silver → Gold
    marts:
      +schema: gold
      +materialized: table